global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'service-a'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['service-a:5000']

  - job_name: 'service-b'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['service-b:5000']